# Generated by Django 2.2.4 on 2019-08-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20190815_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
